# Translations template for keystone.
# Copyright (C) 2016 ORGANIZATION
# This file is distributed under the same license as the keystone project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: keystone 9.0.1.dev10\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-05-04 06:55+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.2.0\n"

#: keystone/notifications.py:336
msgid "Failed to construct notifier"
msgstr ""

#: keystone/notifications.py:439
#, python-format
msgid "Failed to send %(res_id)s %(event_type)s notification"
msgstr ""

#: keystone/notifications.py:706
#, python-format
msgid "Failed to send %(action)s %(event_type)s notification"
msgstr ""

#: keystone/assignment/core.py:688
#, python-format
msgid "Circular reference found role inference rules - %(prior_role_id)s."
msgstr ""

#: keystone/catalog/core.py:75
#, python-format
msgid "Malformed endpoint - %(url)r is not a string"
msgstr ""

#: keystone/catalog/core.py:80
#, python-format
msgid "Malformed endpoint %(url)s - unknown key %(keyerror)s"
msgstr ""

#: keystone/catalog/core.py:88
#, python-format
msgid ""
"Malformed endpoint '%(url)s'. The following type error occurred during "
"string substitution: %(typeerror)s"
msgstr ""

#: keystone/catalog/core.py:94
#, python-format
msgid ""
"Malformed endpoint %s - incomplete format (are you missing a type "
"notifier ?)"
msgstr ""

#: keystone/common/openssl.py:90
#, python-format
msgid "Command %(to_exec)s exited with %(retcode)s - %(output)s"
msgstr ""

#: keystone/common/openssl.py:114
#, python-format
msgid "Failed to remove file %(file_path)r: %(error)s"
msgstr ""

#: keystone/common/utils.py:267
msgid ""
"Error setting up the debug environment. Verify that the option --debug-"
"url has the format <host>:<port> and that a debugger processes is "
"listening on that port."
msgstr ""

#: keystone/common/environment/eventlet_server.py:112
#, python-format
msgid "Could not bind to %(host)s:%(port)s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:211
msgid "Server error"
msgstr ""

#: keystone/endpoint_policy/core.py:131 keystone/endpoint_policy/core.py:231
#, python-format
msgid ""
"Circular reference or a repeated entry found in region tree - "
"%(region_id)s."
msgstr ""

#: keystone/federation/idp.py:440
#, python-format
msgid "Error when signing assertion, reason: %(reason)s%(output)s"
msgstr ""

#: keystone/oauth1/core.py:135
msgid "Cannot retrieve Authorization headers"
msgstr ""

#: keystone/resource/core.py:728
#, python-format
msgid ""
"Asked to convert a non-domain project into a domain - Domain: "
"%(domain_id)s, Project ID: %(id)s, Project Name: %(project_name)s"
msgstr ""

#: keystone/resource/core.py:831
#, python-format
msgid ""
"Circular reference or a repeated entry found projects hierarchy - "
"%(project_id)s."
msgstr ""

#: keystone/resource/core.py:904
msgid "Failed to create the default domain."
msgstr ""

#: keystone/resource/core.py:1479 keystone/resource/V8_backends/sql.py:100
#: keystone/resource/V8_backends/sql.py:119
#: keystone/resource/backends/sql.py:137 keystone/resource/backends/sql.py:156
#, python-format
msgid ""
"Circular reference or a repeated entry found in projects hierarchy - "
"%(project_id)s."
msgstr ""

#: keystone/resource/core.py:1660
#, python-format
msgid ""
"Unexpected results in response for domain config - %(count)s responses, "
"first option is %(option)s, expected option %(expected)s"
msgstr ""

#: keystone/token/provider.py:334
#, python-format
msgid "Unexpected error or malformed token determining token expiry: %s"
msgstr ""

#: keystone/token/persistence/backends/kvs.py:236
#, python-format
msgid ""
"Reinitializing revocation list due to error in loading revocation list "
"from backend.  Expected `list` type got `%(type)s`. Old revocation list "
"data: %(list)r"
msgstr ""

#: keystone/token/providers/common.py:728
msgid "Failed to validate token"
msgstr ""

#: keystone/token/providers/pki.py:52
msgid "Unable to sign token"
msgstr ""

#: keystone/token/providers/fernet/utils.py:42
#, python-format
msgid ""
"Either [fernet_tokens] key_repository does not exist or Keystone does not"
" have sufficient permission to access it: %s"
msgstr ""

#: keystone/token/providers/fernet/utils.py:66
#, python-format
msgid "Unable to convert Keystone user or group ID. Error: %s"
msgstr ""

#: keystone/token/providers/fernet/utils.py:83
msgid ""
"Failed to create [fernet_tokens] key_repository: either it already exists"
" or you don't have sufficient permissions to create it"
msgstr ""

